#pragma once

#include <TFT_eSPI.h>
#include <LittleFS.h>

#define THEME_BACKGROUND_COLOR TFT_BLACK
#define THEME_PRIMARY_COLOR TFT_GREEN
#define THEME_INVERTED_COLOR THEME_BACKGROUND_COLOR
#define SPIFFS_STORAGE LittleFS
#define LATEST_COLOR_SCHEME_INDEX 2
